Improve debian packaging

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,4 +1,46 @@
 #!/bin/sh
+# postrm script for eve-ng-integration
+#
+# see: dh_installdeb(1)
 
-# Update cache of .desktop file MIME types
+set -e
+
+# summary of how this script can be called:
+#   * <postrm> `remove'
+#   * <postrm> `purge'
+#   * <old-postrm> `upgrade' <new-version>
+#   * <new-postrm> `failed-upgrade' <old-version>
+#   * <new-postrm> `abort-install'
+#   * <new-postrm> `abort-install' <old-version>
+#   * <new-postrm> `abort-upgrade' <old-version>
+#   * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+# for details, see /usr/share/doc/packaging-manual/
+
+case "$1" in
+	upgrade)
+		exit 0
+		;;
+	remove|purge)
+		true
+		;;
+	failed-upgrade|abort-install|abort-upgrade)
+		exit 0
+		;;
+	*)
+		echo "prerm called with unknown argument \`$1'" >&2
+		exit 1
+		;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+# build cache database of MIME types handled by desktop files
 update-desktop-database -q || true
+
+# build the Shared MIME-Info database cache
+update-mime-database -n /usr/share/mime || true
+
+exit 0
